// acerca-nosotros
export const galeria = [
    {
      id: 1,
      image: "/card1.jpg",
      estudio: "/serv3.jpg",
      name: " Santiago Semmino ARQ.",
      rol: "@santiagosemino",
      link:"//www.instagram.com/ssa_estudio/",
      mail:"santiagosemino@ssaestudio.com",
      linkemail:"//mailto:santiagosemino@gmail.com",
      descripcion: "Mi nombre es Santiago Semino, nací en Rosario, Argentina, en el año 1978. Soy arquitecto egresadode la Universidad Nacional de Rosario, en el año 2008. En el año 2008 fui socio fundador de 7MArquitectura, en el 2009 hice un posgrado sobre Diseño Sustentable en la Universidad de Palermo.En el año 2013 funde SSA estudio, tratando de fusionar la arquitectura y el diseño en todas sus fases",
    },
    {
      id: 2,
      image: "/card1.jpg",
      estudio: "/photo2.jpg",
      name: " Fernando Fola M.M.O",
      link:"//www.instagram.com/ssa_estudio/",
      mail:"santiagosemino@ssaestudio.com",
      linkemail:"//mailto:santiagosemino@gmail.com",
      rol: "@fernandofola",
      descripcion: ""
    },
    {
      id: 3,
      image: "/card1.jpg",
      estudio: "/bn1.jpg",
      name: " Jeremias Nolli M.M.O",
      link:"//www.instagram.com/ssa_estudio/",
      mail:"santiagosemino@ssaestudio.com",
      linkemail:"//mailto:santiagosemino@gmail.com",
      rol: "@jeremiasnoli",
      descripcion: ""
    },
  
    {
      id: 4,
      image: "/card5.jpg",
      name: " Lucia Sanchez ARQ.",
      link:"//www.instagram.com/ssa_estudio/",
      mail:"santiagosemino@ssaestudio.com",
      linkemail:"//mailto:santiagosemino@gmail.com",
      estudio: "/01.jpg",
      rol: "@LuciaSanchez",
      descripcion: ""
    },
    {
      image: "/card5.jpg",
      id: 5,
      name: " Agostina Selzer DIS.",
      link:"//www.instagram.com/ssa_estudio/",
      mail:"santiagosemino@ssaestudio.com",
      linkemail:"//mailto:santiagosemino@gmail.com",
      rol: "@agos.selzer",
      descripcion: ""
    },
    {
      image: "/card1.jpg",
      id: 6,
      name: " Luisina Viglione ADM. ",
      link:"//www.instagram.com/ssa_estudio/",
      mail:"santiagosemino@ssaestudio.com",
      linkemail:"//mailto:santiagosemino@gmail.com",
      rol: "@LuisinaViglione",
      descripcion: ""
    },
    {
      image: "/card1.jpg",
      id: 7,
      name: " Federico Galassi DEV.",
      link:"//www.instagram.com/ssa_estudio/",
      mail:"federico.galassi9@gmail.com",
      linkemail:"//mailto:santiagosemino@gmail.com",
      rol: " @Federicogalassi_ ",
      descripcion: ""
    },
  ];
  export const colab2 = [
    
    {
      id: 1,
      name: "Julieto Veron",
    },
    {
      id: 3,
      name: "Fati Maranessi",
    },
    {
      id: 4,
      name: "Guillermina Garcia Cassis",
    },
    {
      id: 5,
      name: "Carla Paone",
    },{
      id: 6,
      name: "German Cardonatto",
    },
    {
      id: 7,
      name: "Emiliano Esmores",
    },
    {
      id: 8,
      name: "Mauro Canullo",
    },
    {
      id: 9,
      name: "David Mussi",
    },
    {
      id: 10,
      name: "Franco Topa",
    },
    {
      id: 11,
      name: "Leandro Herrera",
    },
    {
      id: 12,
      name: "Manuel Barbieri",
    },
    {
      id: 13,
      name: "Belen Pepe",
    },
    {
      id: 14,
      name: "Cecilia Mazza",
    },
    {
      id: 15,
      name: "Ignacio Galoppo",
    },
    {
      id: 16,
      name: "Eugenia Valvason",
    },
    {
      id: 17,
      name: "Varinia Mateo",
    },
    {
      id: 18,
      name: "Dulce Scladini",
    },
  ];
  export const colab3 = [

  ]
  export const colab = [
    
    
  
    
  ];
  export const colaboradores = [
    {
      id: 1,
      name: "Ing. Rita Campodonico",
    },
    {
      id: 3,
      name: "Ing. Omar Norris ",
    },
    {
      id: 4,
      name: "Ing. Fernando Tettamanti (PLEXA)",
    },
    {
      id: 5,
      name: "Ing. Fernando Guardianelli",
    },
    {
      id: 6,
      name: "Renders Yamila Baleani",
    },
    {
      id: 7,
      name: "Renders Maximiliano Velazquez",
    },
    {
      id: 8,
      name: "Diseñador Industrial Alejandro Alfano Curbelo",
    },
    {
      id: 9,
      name: "Gestión Municipal Jorgelina Selle",
    },
  ];
export const info  = [
  {
    title: "Estudio SSA",
    descripcion: `”Somos un equipo interdisciplinario enfocado en el diseño y la
    arquitectura, nos dedicamos al diseño de todo tipo de proyectos de
    diferentes escalas, diseño de mobiliario y objetos, sistemas modulares,
    y a concursos nacionales e internacionales.
    Nuestra oficina está impulsada por arquitectos, ingenieros,
    interioristas, diseñadores industriales, y diseñadores gráficos, que
    diseñan y desarrollan conjuntamente proyectos desde los primeros
    bocetos hasta la supervisión final en obra. En nuestro proceso de
    trabajo aparece el diseño y la sustentabilidad como eje principal de
    nuestros proyectos.
    El estudio de los nuevos sistemas constructivos, la evolución y
    transformación de las ciudades, la innovación tecnológica, y el diseño
    eficiente es lo que nos motiva a seguir creciendo…”
    `
  },]
  // prensa
  export const prensa = [
    {
      img: "/mc.jpg",
      number: 30,
      mes: "Junio",
      año: 2023,
      title: "Mundo Construcción",
      tipo: "ENTREVISTA",
      enlace:
      "https://www.youtube.com/watch?v=AgZftXHh8G0",
    },
    {
      img: "/Tyq.jpg",
      number: 16,
      mes: "Marzo",
      año: 2023,
      title: "Terrenos y Quintas ",
      tipo: "NOTA",
      enlace:
      "https://notas.terrenosyquintas.com/construccion-en-seco-la-tendencia-que-reduce-costos/",
    },
    {
      img: "/dp.jpg",
      number: 26,
      mes: "Mayo",
      año: 2020,
      title: "D.Y Patil University (Pune-India)",
      tipo: "LECTURE",
      enlace:
      "https://drive.google.com/file/d/1VOTVjd2oSF_yYT8HyGO5b0-sTzZ10KRj/view",
    },
    {
      img: "/rn.jpg",
      number: 28,
      mes: "Agosto",
      año: 2019,
      title: " Revista Noticias",
      tipo: "NOTA",
      enlace:
      "https://noticias.perfil.com/noticias/general/2019-09-18-santiago-semino-arquitectos-nuevas-formas-de-habitar.phtml",
    },
      {
        img: "/cs.jpg",
        number: 11,
        mes: "Junio",
        año: 2016,
        title: " Construcción Sustentable U.T.N.",
        tipo: "CHARLA",
        enlace:
          "https://noticias.perfil.com/noticias/general/2019-09-18-santiago-semino-arquitectos-nuevas-formas-de-habitar.phtml",
      },
    {
      img: "/ci.jpg",
      number: 30,
      mes: "Noviembre",
      año: 2010,
      title: "Club Imperial - Rosario",
      tipo: "WORDPRESS",
      enlace:
        "https://clubimperialrosario.wordpress.com/",
      enlace2:
        "https://www.pagina12.com.ar/diario/suplementos/rosario/12-23767-2010-05-29.html",
    },
  ];

  // arquitectura
  
  export const Arquitectura = [
   
    {
      id: 6,
      proyect: "STAND MERCADO DEL PATIO",
      name: "STAND MERCADO DEL PATIO",
      ubi: "Rosario, Santa Fe (ARG)",
      img: "/stand4.jpg",
      descripcion:"  ...",
      images: [
        { src: "/stand4.jpg", alt: "Description 2" },
        { src: "/stand1.jpg", alt: "Description 1" },
        { src: "/stand2.jpg", alt: "Description 2" },
        { src: "/stand3.jpg", alt: "Description 2" },
      ],
      activites: 10,
      places: 12,
      days: "1week",
      year: 2017,
      link: "/Interiores",
    },
    {
      id: 11,
      proyect: "SALON DE USOS MULTIPLES",
      name: "SALON DE USOS MULTIPLES",
      img: "/epportada.jpg",
      ubi:"Concordia, Entre Rios(ARG)",
      descripcion:"  ...",
      images: [
        { src: "/ep1.jpg", alt: "Description 1" },
        { src: "/ep2.jpg", alt: "Description 1" },
        { src: "/ep3.jpg", alt: "Description 1" },
        { src: "/epportada.jpg", alt: "Description 1" },
        { src: "/ep4.jpg", alt: "Description 1" },
        { src: "/ep5.jpg", alt: "Description 1" },
        { src: "/CAP2.jpg", alt: "Description 2" },,
      ],
      activites: 10,
      places: 12,
      days: "1week",
      year: 2017
      ,
      link: "/Interiores",
    },
    {
      id: 5,
      proyect: "REFORMA VESTUARIO",
      name: "REFORMA VESTUARIO",
      ubi: "Fisherton, Santa Fe(ARG)",
      img: "/jcr1.jpg",
      descripcion:"  ...",
      images: [
        { src: "/JCR4.jpg", alt: "Description 2" },
        { src: "/JCR5.jpg", alt: "Description 2" },
        { src: "/JCR6.jpg", alt: "Description 2" },
        { src: "/jcr1.jpg", alt: "Description 1" },
        { src: "/JCR7.jpg", alt: "Description 2" },
        { src: "/JCR8.jpg", alt: "Description 2" },
        { src: "/JCR9.jpg", alt: "Description 2" },
        { src: "/jcr13.jpg", alt: "Description 2" },
        { src: "/jcr21.jpg", alt: "Description 2" },
      ],
      activites: 10,
      places: 12,
      days: "1week",
      year: 2016,
      link: "/Muebles",
    },
   
    {
      id: 7,
      proyect: "INFINITE RIDE",
      name: "INFINITE RIDE",
      ubi: "Perez, Santa Fe(ARG)",
      img: "/IFPORTADA.jpg",
      descripcion:" ...",
      images: [
        { src: "/IF1.jpg", alt: "Description 1" },
        { src: "/IF2.jpg", alt: "Description 1" },
        { src: "/IF3.jpg", alt: "Description 2" },
        { src: "/IF4.jpg", alt: "Description 2" },
        { src: "/IF5.jpg", alt: "Description 2" },
        { src: "/IF6.jpg", alt: "Description 2" },
        { src: "/IFPORTADA.jpg", alt: "Description 2" },
        { src: "/IF7.jpg", alt: "Description 2" },
        { src: "/IF8.jpg", alt: "Description 2" },
        { src: "/IF9.jpg", alt: "Description 2" },
      ],
      activites: 10,
      places: 12,
      days: "1week",
      year: 2015,
      link: "/Interiores",
    },
  
    {
      id: 9,
      proyect: "VIVIENDA MULTIFAMILIAR",
      name: "VIVIENDA MULTIFAMILIAR",
      img: "/BPORTADA.jpg",
      ubi:"Balneario Buenos Aires, Uruguay (UY)",
      descripcion:"....",
      images: [
        { src: "/B1.jpg", alt: "Description 1" },
        { src: "/BPORTADA.jpg", alt: "Description 2" },
        { src: "/B3.jpg", alt: "Description 2" },
        { src: "/B4.jpg", alt: "Description 2" },
        { src: "/B5.jpg", alt: "Description 2" },
        
      ],
      activites: 10,
      places: 12,
      days: "1week",
      year: 2011,
      link: "/Interiores",
    },
    
    {
      id: 4,
      proyect: "VIVIENDA MULTIFAMILIAR",
      name: "VIVIENDA MULTIFAMILIAR",
      ubi: "Mar Azul, Provincia de Buenos Aires (ARG)",
      img: "/polli3.jpg",
      descripcion:"  Esta vivienda esta ubicada en Mar Azul, un pueblo sobre el mar Atlantico.el desafio de este proyecto era desarrollar la vivienda sin tocar los arboles y un terreno con una geografia que su parte posterior estaba por debajo del nivel de calle, o sea con una cota descendente desde el frente hacia el fondo del mismo.La vivienda era para una familia con hijos que ya empezaban a rtener su independencia,y nevesitaban que la vivienda esta separada en 2 unidades con ingreso privado.En la planta del nivel de calle se diseño la vivienda proincipal con cocina, comedor, estar, 2 habitaciones y un baño compartido.En el nivel inferior, descendiendo por el lateral, se accedia a la unidad secundaria ",
      images: [
        { src: "/polli3.jpg", alt: "Description 2" },
        { src: "/polli4.jpg", alt: "Description 2" },
        { src: "/polli5.jpg", alt: "Description 2" },
        { src: "/polli8.jpg", alt: "Description 2" },
        { src: "/polli6.jpg", alt: "Description 2" },
        { src: "/polli1.jpg", alt: "Description 1" },
        { src: "/polli.jpg", alt: "Description 2" },
      ],
      activites: 10,
      places: 12,
      days: "1week",
      year: 2011,
      link: "/Edificios",
    },
    
    {
      id: 2,
      proyect: "Housing San Eduardo",
      name: "Housing San Eduardo",
      ubi: "San Eduardo, Rosario (ARG)",
      img: "/2hse.jpg",
      descripcion:"  Este proyecto consistia en diseñar 5 viviendas unifamiliaresen terrenos angostos, manteniendo la intimidad de las visuales.Cada vivienda, se penso en desarrollarla en medios niveles,para generar distintas visuales en diferentes alturas. el programa incluia, cochera para 2 vehiculos, cocina, comedor, estarlavadero, toillete y una expansion con parrillero.en el primer nivel estaban las habitaciones secundarias, y en el ultimo nivella habitacion principal y un espacio de relax.",
      images: [
        { src: "/2hse.jpg", alt: "Description 1" },
        { src: "/hse1.jpg", alt: "Description 2" },
        { src: "/hse2.jpg", alt: "Description 2" },
        { src: "/hse3.jpg", alt: "Description 2" },
        { src: "/hse4.jpg", alt: "Description 2" },
        { src: "/hse5.jpg", alt: "Description 2" },
        { src: "/hse9.jpg", alt: "Description 2" },
        { src: "/hse6.jpg", alt: "Description 2" },
        { src: "/hse7.jpg", alt: "Description 2" },
        { src: "/hse8.jpg", alt: "Description 2" },
        { src: "/hse10.jpg", alt: "Description 2" },
        { src: "/hse11.jpg", alt: "Description 2" },
      ],
      activites: 10,
      places: 12,
      days: "1week",
      year: 2010,
      link: "/Moda",
    },
    {
      id: 11,
      proyect: "CLUB IMPERIAL",
      name: "CLUB IMPERIAL",
      img: "/CB14.jpg",
      ubi:"Rosario, Santa Fe (ARG)",
      descripcion:" La propuesta de este proyecto era diseñar un club de musica, en un entorno muy intimos donde el artista pueda dar un show en contacto y relacion directa con el publico.Despues de buscar varios lugares, dimos con la Mision del Marinero, un lugar con mucha historia en el centro de la ciudad de Rosario.Esta vieja casona junto con su Iglesia Evangelica, recibia y brindaba hospedaje a marineros extranjeros, en los años 50.El programa incluia mantener la casona original y conectarse a ellaa travez de una cubierta metalica que funcionaba como quinta fachada, ya que desde la Av. Belgrano se podia ver esa cubierta. La idea fue fasetar el techo, ya que esos quiebres nos darian planos irregulares y servirian al interior en la parte acustica.En el interior se propusieron materiales con mucha absorcion sonora, como los telones que funcionaban para cerrar la sala, alfombra en el piso, y sus paredes y cielorasos revestirlos con placas de madera. La Sala contaba con 220 butacas, con una mesa de apoyobebidascada 2 butacas. ",
      images: [
        { src: "/CB10.jpg", alt: "Description 1" },
        { src: "/CB11.jpg", alt: "Description 2" },
        { src: "/00portada.jpg", alt: "Description 2" },
        { src: "/CB13.jpg", alt: "Description 2" },
        { src: "/CB14.jpg", alt: "Description 2" },
        { src: "/CB09.jpg", alt: "Description 2" },
        { src: "/CB08.jpg", alt: "Description 2" },
        { src: "/CB07.jpg", alt: "Description 2" },
        { src: "/CB06.jpg", alt: "Description 2" },
        { src: "/CB05.jpg", alt: "Description 2" },
        { src: "/CB4.jpg", alt: "Description 2" },
        { src: "/CB03.jpg", alt: "Description 2" },
        { src: "/CB2.jpg", alt: "Description 2" },
        { src: "/CB01.jpg", alt: "Description 2" },
      ],
      activites: 10,
      places: 12,
      days: "1week",
      year: 2006,
      link: "/Interiores",
    },
   
    {
      id: 11,
      proyect: "Outdoor Gym J.C.R.  ",
      name: "Outdoor Gym J.C.R. ",
      img: "/01PORTADA.jpg",
      ubi:" Fisherton, Rosario (ARG)",
      descripcion:" Este proyecto se penso en poder crear una cubierta, donde poder resgruardar los elementos de gimnasio, pero a la vez abierta para ejercitar al aire libre. Se penso en un recubrimiento metalico perforado y por dentro generando una camara de aire un revestimientoplastico traslucido de color verde para filtre la luz solar, y el interir se tiñe de color verde.",
      images: [
        { src: "/01PORTADA.jpg", alt: "Description 1" },
        { src: "/02SLIDE.jpg", alt: "Description 2" },
        { src: "/02SLIDE.jpg", alt: "Description 2" },
      ],
      activites: 10,
      places: 12,
      days: "1week",
      year: 2006
      ,
      link: "/Interiores",
    },
   
    
   
   
    
  ];

  // concursos 
  export const concursos = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "SONICO",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
      { src: "/photo4.jpg", alt: "Description 2" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "APAGAR",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "Productos",
    name: "TOTEM",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "LARI",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "MR & MS",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "MUNDO",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "ROUND",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "FLIGHT565",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "FLIGHT565",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "FLIGHT565",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "FLIGHT565",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];
//contacto

export const testimonials = [
  {
    id: 1,
    text: "santiagosemino@ssaestudio.com ",
    avatar: "/w2.png",
    link: "//mailto:federico.galassi9@gmail.com",
    href: "//mailto:federico.galassi9@gmail.com",
    icon: "fa fa-envelope",
  },
  {
    id: 2,
    text: " 54-3416622170 ",
    avatar: "/w2.png",
    link: "//wa.link/a6w9de",
    href: "//wa.link/a6w9de",
    icon: "fa-brands fa-whatsapp",
  },
  {
    id: 3,
    text: "Linkedin",
    avatar: "/w2.png",
    link: "//www.linkedin.com/in/santiago-semino-arquitectos-60406218b/",
    href: "//www.linkedin.com/in/santiago-semino-arquitectos-60406218b/",
    icon: "fa-brands fa-linkedin",
  },
  {
    id: 4,
    text: "Instagram",
    avatar: "/w2.png",
    link: "//www.instagram.com/ssa_estudio/",
    href: "//www.instagram.com/ssa_estudio/",
    icon: "fa-brands fa-instagram",
  },
  {
    id: 5,
    text: "Facebook",
    avatar: "/w2.png",
    link: "//www.facebook.com/ssaestudio?locale=es_LA",
    href: "//www.facebook.com/ssaestudio?locale=es_LA",
    icon: "fa-brands fa-facebook-messenger",
  },
];
//mobile

export const mobile = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "md1",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "md2",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "md",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "Productos",
    name: "md3",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "md4",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "md5",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "md6",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "md7",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "md",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "md",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "md",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "md",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];

//mobiliario

export const mobiliario = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "MOBILIARIO",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "MOBILIARIO",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "productos",
    name: "MOBILIARIO",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "MOBILIARIO",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "MOBILIARIO",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "MOBILIARIO",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "aMOBILIARIOrq5",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "aMOBILIARIOrq4",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "MOBILIARIO",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "MOBILIARIO",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "MOBILIARIO",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];

//modular

export const modular = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "MODULAR",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "MODULAR",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "productos",
    name: "MODULAR",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "MODULAR",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "MODULAR",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "MODULAR",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "MODULAR",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "MODULAR",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "MODULAR",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "MODULAR",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "MODULAR",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];
// MODULOS
export const modulos = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "Recyclable1",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "Recyclable1",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "Productos",
    name: "Recyclable1",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "Recyclable1",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "MR & Recyclable1",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "Recyclable1",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "Recyclable1",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "Recyclable1",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "Recyclable1",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "Recyclable1",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "Recyclable1",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    images: [
      { src: "/photo3.jpg", alt: "Description 1" },
      { src: "/photo4.jpg", alt: "Description 2" },
    ],
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];
//galery
export const galery = [
  {
    id: 1,
    proyect: "Arquitectura",
    name: "Arquitectura",
    img: "/g51.jpg",
    activites: 10,
   /*  places: 32, */
    days: "1week",
    price: 1.2,
    link: "/Arquitectura",
  },
  {
    id: 2,
    proyect: "CONCURSOS",
    name: "Concursos",

    img: "/g6.jpg",
    activites: 1450,
    /* places: 132, */
    days: "1week",
    price: 1.2,
    link: "/Concursos",
  },
  {
    id: 3,
    proyect: "DISEÑO MOBILIARIO",
    name: "Mobiliario",
    img: "/g1.jpg",
    activites: 23,
   /*  places: 54, */
    days: "1week",
    price: 1.2,
    link: "/Mobiliario",
  },
  {
    id: 4,
    proyect: "ARQUITECTURA MODULAR",
    name: "Modulos",
    img: "/g71.jpg",
    activites: 10,
    /* places: 200, */
    days: "1week",
    price: 1.2,
    link: "/Modulos",
  },
  
  {
    proyect: "MOBILE",
    name: "Mobile ",
    
    img: "/g21.jpg",
    id: 5,
    activites: 45,
    /* places: 46, */
    days: "1week",
    price: 1.2,
    link: "/MobileDesigne",
  },
 
];
//servicios

export const servicios = [
  {
    id: 1,
    name: "PROYECTOS DE ARQUITECTURA",
    links: [
      { name: "Housing San Eduardo", link: "https://ssaarquitectos.vercel.app/Arquitectura-photo/0" },
      { name: "Housing San Eduardo", link: "https://ssaarquitectos.vercel.app/Arquitectura-photo/0" },
      { name: "Housing San Eduardo", link: "https://ssaarquitectos.vercel.app/Arquitectura-photo/0" },
    ],
    descripcion: `Diseñamos proyectos de arquitectura a medida, como viviendas, edificios en altura, edificios comerciales,
    edificios de usos múltiples, proyectos de urbanismo y paisajismo. La sustentabilidad y el diseño eficiente
    aparecen en nuestros primeros bocetos, como parte conjunta de nuestro proceso.`,
 
  },
  {
    id: 2,
    name: "GESTIÓN, PLANIFICACIÓN Y DIRECCIÓN DE OBRAS",
    links: [
      { name: "Housing San Eduardo", link: "https://ssaarquitectos.vercel.app/Arquitectura-photo/0" },
      { name: "Housing San Eduardo", link: "https://ssaarquitectos.vercel.app/Arquitectura-photo/0" },
      { name: "Housing San Eduardo", link: "https://ssaarquitectos.vercel.app/Arquitectura-photo/0" },
    ],
    descripcion: `Nos encargamos del servicio de Gestión, Planificación y Dirección de todo tipo de obras, de
    diferentes escalas y complejidad.
    Coordinamos el proceso diario de la dirección de obras, haciendo el control de calidad de los
    materiales y de las diferentes tareas de los contratistas involucrados.
    `,
   
  },
  {
    id: 3,
    name: " DISEÑO Y FABRICACIÓN DE MOBILIARIO",
    links: [
      { name: "Housing San Eduardo", link: "https://ssaarquitectos.vercel.app/Arquitectura-photo/0" },
      { name: "Housing San Eduardo", link: "https://ssaarquitectos.vercel.app/Arquitectura-photo/0" },
      { name: "Housing San Eduardo", link: "https://ssaarquitectos.vercel.app/Arquitectura-photo/0" },
    ],
    descripcion:
    `Diseñamos y fabricamos muebles y objetos de diseño.
    Para nosotros es muy importante el diseño del mobiliario de nuestros proyectos de
    arquitectura, es por eso que diseñamos conjuntamente el mobiliario para todos los
    ambientes interiores del proyecto, estudiando cada detalle y materiales.
    `,
  },
  {
    id: 4,
    name: "DISEÑO DE ESTRUCTURAS MODULARES",
    links: [
      { name: "Housing San Eduardo", link: "https://ssaarquitectos.vercel.app/Arquitectura-photo/0" },
      { name: "Housing San Eduardo", link: "https://ssaarquitectos.vercel.app/Arquitectura-photo/0" },
      { name: "Housing San Eduardo", link: "https://ssaarquitectos.vercel.app/Arquitectura-photo/0" },
    ],
    descripcion:
    `Diseñamos estructuras modulares y transportables, para diferentes tipos de usos, tales como:
    locales comerciales, módulos de marca, habitaciones de hotel, viviendas, oficinas,
    laboratorios, etc. Estos módulos se pueden instalar en cualquier tipo de terreno y clima, están
    preparados para soportar los traslados, generan su propia energía y almacenan el agua de
    lluvia.
   `,
   
  },
  
];

