// acerca-nosotros
export const galeria = [
    {
      id: 1,
      image: "/card1.jpg",
      estudio: "/serv3.jpg",
      name: "Santiago Semmino",
      rol: "[Arquitecto]",
      descripcion: "Departamento Arquitectura",
    },
    {
      id: 2,
      image: "/card1.jpg",
      estudio: "/photo2.jpg",
      name: "Fernando Fola",
      rol: "[Maestro mayor de obras]",
      descripcion: "Departamento Arquitectura",
    },
    {
      id: 3,
      image: "/card2.jpg",
      estudio: "/bn1.jpg",
      name: "Jeremias Nolli",
      rol: "[Maestro mayor de obras]",
      descripcion: "Departamento Arquitectura",
    },
  
    {
      id: 4,
      image: "/card2.jpg",
      name: "Lucia Sanchez",
      estudio: "/01.jpg",
      rol: "[Arquitecta]",
      descripcion: "Departamento Arquitectura",
    },
    {
      image: "/card5.jpg",
      id: 5,
      name: "Agostina Selzer ",
      rol: "[Diseñadora]",
      descripcion: "Departamento Diseño",
    },
    {
      image: "/card1.jpg",
      id: 6,
      name: "Luisina Viglione ",
      rol: "[Administracion]",
      descripcion: "Departamento Adminsitrativo",
    },
    {
      image: "/card1.jpg",
      id: 7,
      name: "Federico Galassi",
      rol: "[Desarrollador Web]",
      descripcion: "Departamento Tecnologia",
    },
  ];
  export const colab = [
    {
      id: 1,
      name: "Guillermina Garcia Cassis",
    },
    {
      id: 3,
      name: "Carla Paone ",
    },
    {
      id: 4,
      name: "German Cardonato",
    },
    {
      id: 5,
      name: "Emiliano Esmores",
    },
    {
      id: 6,
      name: "Mauro Canullo ",
    },
    {
      id: 7,
      name: "Julieta Veron",
    },
    {
      id: 8,
      name: "Franco Topa",
    },
    {
      id: 9,
      name: "Leandro Herrera",
    },
    {
      id: 10,
      name: "Manuel Barbieri",
    },
    {
      id: 11,
      name: "Belen Pepe",
    },
    {
      id: 12,
      name: "Cecilia Mazza",
    },
    {
      id: 13,
      name: "Ignacio Galoppo",
    },
    {
      id: 14,
      name: "Eugenia Valvason",
    },
    {
      id: 15,
      name: "Varinia Mateo",
    },
    {
      id: 16,
      name: "Dulce Scaldini",
    },
  ];
  export const colaboradores = [
    {
      id: 1,
      name: "Ing. Omar Norris",
    },
    {
      id: 3,
      name: "Ing. Rita Campodónico ",
    },
    {
      id: 4,
      name: "Ing. Fernando",
    },
    {
      id: 5,
      name: "Renders - Yamila Baleani",
    },
    {
      id: 6,
      name: "Renders - Maxi Velazques ",
    },
    {
      id: 7,
      name: "Dis Industrial - Alejandro Alfano",
    },
    {
      id: 8,
      name: "Dis Industrial - Mauricio Marinucci",
    },
    {
      id: 9,
      name: "Gestión Municipal - Jorgelina Selle",
    },
  ];
export const info  = [
  {
    title: "Estudio SSA",
    descripcion: ` Somos un equipo interdisciplinario enfocado en el diseño y la
    arquitectura, con dedicación a proyectos de todo tipo de escala,
    diseño de mobiliario, objetos, sistemas modulares, y con activa
    participación a concursos nacionales e internacionales. Nuestra
    oficina está impulsada por jóvenes arquitectos, ingenieros,
    interioristas, diseñadores gráficos, industriales que diseñan y
    desarrollan conjuntamente proyectos desde los primeros bocetos hasta
    la supervisión final en obra. En nuestro proceso de trabajo aparece
    el diseño sustentable como eje principal de nuestros proyectos. El
    estudio de los nuevos sistemas de construcción, la transformación y
    evolución de las ciudades, la innovación tecnológica, y el diseño
    eficiente es lo que nos motiva a seguir creciendo.`
  },]
  // prensa
  export const prensa = [
    {
      img: "/serv1.jpg",
      number: 11,
      mes: "Junio",
      año: 2016,
      title: " Construcción Sustentable U.T.N.",
      tipo: "CHARLA",
      enlace:
        "https://noticias.perfil.com/noticias/general/2019-09-18-santiago-semino-arquitectos-nuevas-formas-de-habitar.phtml",
    },
    {
      img: "/photo3.jpg",
      number: 28,
      mes: "Agosto",
      año: 2019,
      title: " Revista Noticias",
      tipo: "NOTA",
      enlace:
        "https://noticias.perfil.com/noticias/general/2019-09-18-santiago-semino-arquitectos-nuevas-formas-de-habitar.phtml",
    },
    {
      img: "/serv2.jpg",
      number: 26,
      mes: "Mayo",
      año: 2020,
      title: "D.Y Patil University (Pune-India)",
      tipo: "LECTURE",
      enlace:
        "https://drive.google.com/file/d/1VOTVjd2oSF_yYT8HyGO5b0-sTzZ10KRj/view",
    },
    {
      img: "/serv3.jpg",
      number: 16,
      mes: "Marzo",
      año: 2023,
      title: "Terrenos y Quintas ",
      tipo: "NOTA",
      enlace:
        "https://notas.terrenosyquintas.com/construccion-en-seco-la-tendencia-que-reduce-costos/",
    },
    {
      img: "/photo2.jpg",
      number: 30,
      mes: "Junio",
      año: 2023,
      title: "Mundo Construcción",
      tipo: "ENTREVISTA",
      enlace:
        "https://open.spotify.com/episode/3JjW62ePXmv7W1ATY3r4nk?si=Ev-5LthNRx-3NDiOGf3TaQ",
    },
  ];

  // arquitectura
  
  export const Arquitectura = [
    {
      id: 1,
      proyect: "Exibicion de arte",
      name: "arq11",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      ubi: "galeria de arte sidney",
      img: "/e1.png",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2023,
      link: "/Exibicion",
    },
    {
      id: 2,
      proyect: "Moda",
      name: "arq10",
      ubi: "galeria de arte auckland",
      img: "/e2.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2021,
      link: "/Moda",
    },
    {
      id: 3,
      proyect: "productos",
      name: "arq9",
      ubi: "galeria de arte dobrazil",
      img: "/e3.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 1999,
      link: "/Productos",
    },
    {
      id: 4,
      proyect: "Edificios",
      name: "arq8",
      ubi: "galeria de arte otawa",
      img: "/e4.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2022,
      link: "/Edificios",
    },
    {
      id: 5,
      proyect: "Muebles",
      name: "arq7",
      ubi: "galeria de arte japon",
      img: "/e5.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2022,
      link: "/Muebles",
    },
    {
      id: 6,
      proyect: "Interiores",
      name: "arq6",
      ubi: "galeria de arte rusia",
      img: "/e6.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2023,
      link: "/Interiores",
    },
    {
      id: 7,
      proyect: "Interiores",
      name: "arq5",
      ubi: "galeria de arte crespo",
      img: "/e7.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2021,
      link: "/Interiores",
    },
    {
      id: 8,
      proyect: "Interiores",
      name: "arq4",
      img: "/e8.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2022,
      link: "/Interiores",
    },
    {
      id: 9,
      proyect: "Interiores",
      name: "arq3",
      img: "/e8.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2022,
      link: "/Interiores",
    },
    {
      id: 10,
      proyect: "Interiores",
      name: "arq2",
      img: "/e8.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2022,
      link: "/Interiores",
    },
    {
      id: 11,
      proyect: "Interiores",
      name: "arq1",
      img: "/e8.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2022,
      link: "/Interiores",
    },
  ];

  // concursos 
  export const concursos = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "SONICO",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "APAGAR",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "Productos",
    name: "TOTEM",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "LARI",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "MR & MS",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "MUNDO",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "ROUND",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "FLIGHT565",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "FLIGHT565",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "FLIGHT565",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "FLIGHT565",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];
//contacto

export const testimonials = [
  {
    id: 1,
    text: "santiagosemino@ssaestudio.com ",
    avatar: "/w2.png",
    link: "//mailto:federico.galassi9@gmail.com",
    href: "//mailto:federico.galassi9@gmail.com",
    icon: "fa fa-envelope",
  },
  {
    id: 2,
    text: " 54-3416622170 ",
    avatar: "/w2.png",
    link: "//wa.link/a6w9de",
    href: "//wa.link/a6w9de",
    icon: "fa-brands fa-whatsapp",
  },
  {
    id: 3,
    text: "Linkedin",
    avatar: "/w2.png",
    link: "//www.linkedin.com/in/santiago-semino-arquitectos-60406218b/",
    href: "//www.linkedin.com/in/santiago-semino-arquitectos-60406218b/",
    icon: "fa-brands fa-linkedin",
  },
  {
    id: 4,
    text: "Instagram",
    avatar: "/w2.png",
    link: "//www.instagram.com/ssa_estudio/",
    href: "//www.instagram.com/ssa_estudio/",
    icon: "fa-brands fa-instagram",
  },
  {
    id: 5,
    text: "Facebook",
    avatar: "/w2.png",
    link: "//www.facebook.com/ssaestudio?locale=es_LA",
    href: "//www.facebook.com/ssaestudio?locale=es_LA",
    icon: "fa-brands fa-facebook-messenger",
  },
];
//mobile

export const mobile = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "md1",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "md2",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "md",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "Productos",
    name: "md3",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "md4",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "md5",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "md6",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "md7",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "md",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "md",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "md",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "md",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];

//mobiliario

export const mobiliario = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "MOBILIARIO",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "MOBILIARIO",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "productos",
    name: "MOBILIARIO",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "MOBILIARIO",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "MOBILIARIO",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "MOBILIARIO",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "aMOBILIARIOrq5",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "aMOBILIARIOrq4",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "MOBILIARIO",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "MOBILIARIO",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "MOBILIARIO",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];

//modular

export const modular = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "MODULAR",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "MODULAR",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "productos",
    name: "MODULAR",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "MODULAR",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "MODULAR",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "MODULAR",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "MODULAR",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "MODULAR",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "MODULAR",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "MODULAR",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "MODULAR",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];
// MODULOS
export const modulos = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "Recyclable1",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "Recyclable1",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "Productos",
    name: "Recyclable1",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "Recyclable1",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "MR & Recyclable1",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "Recyclable1",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "Recyclable1",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "Recyclable1",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "Recyclable1",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "Recyclable1",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "Recyclable1",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];
//galery
export const galery = [
  {
    id: 1,
    proyect: "Arquitectura",
    name: "Arquitectura",
    img: "/g5.jpg",
    activites: 10,
   /*  places: 32, */
    days: "1week",
    price: 1.2,
    link: "/Arquitectura",
  },
  {
    id: 2,
    proyect: "CONCURSOS",
    name: "Concursos",

    img: "/g6.jpg",
    activites: 1450,
    /* places: 132, */
    days: "1week",
    price: 1.2,
    link: "/Concursos",
  },
  {
    id: 3,
    proyect: "DISEÑO MOBILIARIO",
    name: "Mobiliario",
    img: "/g1.jpg",
    activites: 23,
   /*  places: 54, */
    days: "1week",
    price: 1.2,
    link: "/Mobiliario",
  },
  {
    id: 4,
    proyect: "ARQUITECTURA MODULAR",
    name: "Modulos",
    img: "/g7.jpg",
    activites: 10,
    /* places: 200, */
    days: "1week",
    price: 1.2,
    link: "/Modulos",
  },
  {
    proyect: "MOBILE",
    name: "Mobile ",
    
    img: "/g2.jpg",
    id: 5,
    activites: 45,
    /* places: 46, */
    days: "1week",
    price: 1.2,
    link: "/MobileDesigne",
  },
 
];
//servicios

export const servicios = [
  {
    id: 1,
    name: "Proyectos de Arquitectura",
    links: [
      { name: "Hotel Nhow Berlín", link: "/ASD4" },
      { name: "Fun Factory Múnich", link: "/ASD5" },
      { name: "kado", link: "/ASD6" },
    ],
    descripcion: `Diseñamos proyectos de arquitectura de todo tipo de formato y escala, en nuestro proceso    de trabajo los proyectos están divididos 4 diferentes etapas:`,
    descripcion1: `1. ESTUDIO PRELIMINAR
      Es el estudio preliminar del proyecto, donde analizamos el pedido del cliente, y empezamos a
      diseñarlo.
      De estos primeros bocetos podemos empezar a estimar tipo de sistema constructivo, cantidad de
      niveles de construcción, metros cubiertos, etc. Todos estos datos podemos estimar un costo
      estimado general de obra preliminar, y empezar a definir el programa de necesidades junto con el
      cliente.`,
    descripcion2: `2. ANTEPROYECTO
      Una vez definida la primera etapa, pasamos al anteproyecto, donde empezaremos a diseñar el
      proyecto requerido. En esta etapa entra la parte sustentable, y empieza a mezclarse con el diseño
      del proyecto.
      En esta etapa se le empieza a mostrar al cliente, cierta planimetría y una maqueta digital, donde se
      podrá ver la volumetría, algunos espacios exteriores e interiores, asi como tambien debe exhibir los
      sistemas constructivos propuestos y los elementos más representativos de la estructura e
      instalaciones que puedan tener gravitación en la documentación final del proyecto, esta etapa debe
      estar acompañado por un presupuesto global estimativo.
      El Anteproyecto debe cumplir con las disposiciones del Reglamento de Edificación vigente de la
      ciudad donde se va a implantar el proyecto.`,
    descripcion3: `3. LEGAJO EJECUTIVO
      En esta etapa vamos a poder definir, instalaciones finales, sanitarios, terminaciones
      Se le entrega al cliente una carpeta con toda la planimetría para poder ejecutar la obra, con el
      contratista que el cliente elija.
      Esta carpeta cumplirá con las disposiciones del Reglamento de Edificación e incluirá toda la
      información necesaria para que el constructor confeccione los planos de ejecución
      correspondientes a la ingeniería de detalle.
      El desarrollo de un proyecto debe estar acompañado por sucesivas estimaciones y ajustes de
      cómputos y costos para permitir la evaluación de alternativas morfológicas o de especificación.`,
    descripcion4: `4. GESTIÓN MUNICIPAL
      Ofrecemos el servicio de Gestión municipal en el cual gestionamos Permisos Municipales y/o Finales
      de Obra.
      Permiso de Edificación:
      Para la habilitación y/o permiso de edificación el arquitecto a cargo deberá presentar el
      legajo correspondiente en el colegio de arquitectos y pagar sus respectivos aportes, una vez
      hecho este trámite, deberá presentar el legajo municipal, el cual deberá incluir toda la
      información requerida por el municipio correspondiente.
      Final de Obra
      Este trámite se gestionará y presentará una vez finalizada la obra, presentando las
      correcciones o planos adicionales correspondientes según la reglamentación de cada
      municipio.`,
  },
  {
    id: 2,
    name: "Dirección de Obras",
    links: [
      { name: "Hotel Nhow Berlín", link: "/ASD4" },
      { name: "Fun Factory Múnich", link: "/ASD5" },
      { name: "kado", link: "/ASD6" },
    ],
    descripcion: `Nos encargamos del servicio de Dirección de Obras, desde la planificación previa al comienzo
       de la misma, revisando cada detalle de la parte Técnica, haciendo el control de calidad de la
       ejecución de la mano de obra, hasta la supervisión de las terminaciones finales de obra.`,
    descripcion1: `El Director de Obra junto con el comitente serán los encargados de presupuestar las distintas
      tareasGestion y planificacion de obras, y seleccionar la Mano de Obra, también adjudican las obras a los distintos rubros
      intervinientes`,
    descripcion2: `Todos los presupuestos aprobados de la obra se deberán entregar al Director de Obra, quien
    actualiza la planilla de Cómputo y Presupuesto y deberá presentar la certificación semanal de la
    obra.
    `,
    descripcion3: `LA TAREA DEL DIRECTOR DE OBRA ES EL CONTROL Y LA COORDINACIÓN DE LAS TAREAS`,
  },
  {
    id: 3,
    name: "Gestion y Planificacion de Obras",
    links: [
      { name: "Hotel Nhow Berlín", link: "/ASD4" },
      { name: "Fun Factory Múnich", link: "/ASD5" },
      { name: "kado", link: "/ASD6" },
    ],
    descripcion:
    `Nos encargamos del servicio Gestión y planificación de obras de todo tipo de escala y
    complejidad, coordinando y gestionando día a día las tareas diarias de la obra.`,
    descripcion1:
    `La gestión y planificación es tratar de estar adelantado a las tareas diarias y poder ir gestionando
    con anticipación algunas tareas que requieren un seguimiento más minucioso, y así poder cumplir
    con el cronograma de obra.
    `,
  },
  
];

