// acerca-nosotros
export const galeria = [
    {
      id: 1,
      image: "/card1.jpg",
      estudio: "/serv3.jpg",
      name: "Santiago Semmino",
      rol: "[Arquitecto]",
      descripcion: "Departamento Arquitectura",
    },
    {
      id: 2,
      image: "/card1.jpg",
      estudio: "/photo2.jpg",
      name: "Fernando Fola",
      rol: "[Maestro mayor de obras]",
      descripcion: "Departamento Arquitectura",
    },
    {
      id: 3,
      image: "/card2.jpg",
      estudio: "/bn1.jpg",
      name: "Jeremias Nolli",
      rol: "[Maestro mayor de obras]",
      descripcion: "Departamento Arquitectura",
    },
  
    {
      id: 4,
      image: "/card2.jpg",
      name: "Lucia Sanchez",
      estudio: "/01.jpg",
      rol: "[Arquitecta]",
      descripcion: "Departamento Arquitectura",
    },
    {
      image: "/card5.jpg",
      id: 5,
      name: "Agostina Selzer ",
      rol: "[Diseñadora]",
      descripcion: "Departamento Diseño",
    },
    {
      image: "/card1.jpg",
      id: 6,
      name: "Luisina Viglione ",
      rol: "[Administracion]",
      descripcion: "Departamento Adminsitrativo",
    },
    {
      image: "/card1.jpg",
      id: 7,
      name: "Federico Galassi",
      rol: "[Desarrollador Web]",
      descripcion: "Departamento Tecnologia",
    },
  ];
  export const colab = [
    {
      id: 1,
      name: "Guillermina Garcia Cassis",
    },
    {
      id: 3,
      name: "Carla Paone ",
    },
    {
      id: 4,
      name: "German Cardonato",
    },
    {
      id: 5,
      name: "Emiliano Esmores",
    },
    {
      id: 6,
      name: "Mauro Canullo ",
    },
    {
      id: 7,
      name: "Julieta Veron",
    },
    {
      id: 8,
      name: "Franco Topa",
    },
    {
      id: 9,
      name: "Leandro Herrera",
    },
    {
      id: 10,
      name: "Manuel Barbieri",
    },
    {
      id: 11,
      name: "Belen Pepe",
    },
    {
      id: 12,
      name: "Cecilia Mazza",
    },
    {
      id: 13,
      name: "Ignacio Galoppo",
    },
    {
      id: 14,
      name: "Eugenia Valvason",
    },
    {
      id: 15,
      name: "Varinia Mateo",
    },
    {
      id: 16,
      name: "Dulce Scaldini",
    },
  ];
  export const colaboradores = [
    {
      id: 1,
      name: "Ing. Omar Norris",
    },
    {
      id: 3,
      name: "Ing. Rita Campodónico ",
    },
    {
      id: 4,
      name: "Ing. Fernando",
    },
    {
      id: 5,
      name: "Renders - Yamila Baleani",
    },
    {
      id: 6,
      name: "Renders - Maxi Velazques ",
    },
    {
      id: 7,
      name: "Dis Industrial - Alejandro Alfano",
    },
    {
      id: 8,
      name: "Dis Industrial - Mauricio Marinucci",
    },
    {
      id: 9,
      name: "Gestión Municipal - Jorgelina Selle",
    },
  ];
export const info  = [
  {
    title: "Estudio SSA",
    descripcion: ` Somos un equipo interdisciplinario enfocado en el diseño y la
    arquitectura, con dedicación a proyectos de todo tipo de escala,
    diseño de mobiliario, objetos, sistemas modulares, y con activa
    participación a concursos nacionales e internacionales. Nuestra
    oficina está impulsada por jóvenes arquitectos, ingenieros,
    interioristas, diseñadores gráficos, industriales que diseñan y
    desarrollan conjuntamente proyectos desde los primeros bocetos hasta
    la supervisión final en obra. En nuestro proceso de trabajo aparece
    el diseño sustentable como eje principal de nuestros proyectos. El
    estudio de los nuevos sistemas de construcción, la transformación y
    evolución de las ciudades, la innovación tecnológica, y el diseño
    eficiente es lo que nos motiva a seguir creciendo.`
  },]
  // prensa
  export const prensa = [
    {
      img: "/serv1.jpg",
      number: 11,
      mes: "Junio",
      año: 2016,
      title: " Construcción Sustentable U.T.N.",
      tipo: "CHARLA",
      enlace:
        "https://noticias.perfil.com/noticias/general/2019-09-18-santiago-semino-arquitectos-nuevas-formas-de-habitar.phtml",
    },
    {
      img: "/photo3.jpg",
      number: 28,
      mes: "Agosto",
      año: 2019,
      title: " Revista Noticias",
      tipo: "NOTA",
      enlace:
        "https://noticias.perfil.com/noticias/general/2019-09-18-santiago-semino-arquitectos-nuevas-formas-de-habitar.phtml",
    },
    {
      img: "/serv2.jpg",
      number: 26,
      mes: "Mayo",
      año: 2020,
      title: "D.Y Patil University (Pune-India)",
      tipo: "LECTURE",
      enlace:
        "https://drive.google.com/file/d/1VOTVjd2oSF_yYT8HyGO5b0-sTzZ10KRj/view",
    },
    {
      img: "/serv3.jpg",
      number: 16,
      mes: "Marzo",
      año: 2023,
      title: "Terrenos y Quintas ",
      tipo: "NOTA",
      enlace:
        "https://notas.terrenosyquintas.com/construccion-en-seco-la-tendencia-que-reduce-costos/",
    },
    {
      img: "/photo2.jpg",
      number: 30,
      mes: "Junio",
      año: 2023,
      title: "Mundo Construcción",
      tipo: "ENTREVISTA",
      enlace:
        "https://www.youtube.com/watch?v=AgZftXHh8G0",
    },
  ];

  // arquitectura
  
  export const Arquitectura = [
    {
      id: 1,
      proyect: "Exibicion de arte",
      name: "arq11",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      ubi: "galeria de arte sidney",
      img: "/e1.png",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2023,
      link: "/Exibicion",
    },
    {
      id: 2,
      proyect: "Moda",
      name: "arq10",
      ubi: "galeria de arte auckland",
      img: "/e2.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2021,
      link: "/Moda",
    },
    {
      id: 3,
      proyect: "productos",
      name: "arq9",
      ubi: "galeria de arte dobrazil",
      img: "/e3.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 1999,
      link: "/Productos",
    },
    {
      id: 4,
      proyect: "Edificios",
      name: "arq8",
      ubi: "galeria de arte otawa",
      img: "/e4.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2022,
      link: "/Edificios",
    },
    {
      id: 5,
      proyect: "Muebles",
      name: "arq7",
      ubi: "galeria de arte japon",
      img: "/e5.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2022,
      link: "/Muebles",
    },
    {
      id: 6,
      proyect: "Interiores",
      name: "arq6",
      ubi: "galeria de arte rusia",
      img: "/e6.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2023,
      link: "/Interiores",
    },
    {
      id: 7,
      proyect: "Interiores",
      name: "arq5",
      ubi: "galeria de arte crespo",
      img: "/e7.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2021,
      link: "/Interiores",
    },
    {
      id: 8,
      proyect: "Interiores",
      name: "arq4",
      img: "/e8.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2022,
      link: "/Interiores",
    },
    {
      id: 9,
      proyect: "Interiores",
      name: "arq3",
      img: "/e8.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2022,
      link: "/Interiores",
    },
    {
      id: 10,
      proyect: "Interiores",
      name: "arq2",
      img: "/e8.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2022,
      link: "/Interiores",
    },
    {
      id: 11,
      proyect: "Interiores",
      name: "arq1",
      img: "/e8.png",
      descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
      photo1:"/photo1.jpg",
      photo2:"/photo2.jpg",
      photo3:"/photo3.jpg",
      photo4:"/photo4.jpg",
      activites: 10,
      places: 12,
      days: "1week",
      year: 2022,
      link: "/Interiores",
    },
  ];

  // concursos 
  export const concursos = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "SONICO",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "APAGAR",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "Productos",
    name: "TOTEM",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "LARI",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "MR & MS",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "MUNDO",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "ROUND",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "FLIGHT565",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "FLIGHT565",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "FLIGHT565",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "FLIGHT565",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];
//contacto

export const testimonials = [
  {
    id: 1,
    text: "santiagosemino@ssaestudio.com ",
    avatar: "/w2.png",
    link: "//mailto:federico.galassi9@gmail.com",
    href: "//mailto:federico.galassi9@gmail.com",
    icon: "fa fa-envelope",
  },
  {
    id: 2,
    text: " 54-3416622170 ",
    avatar: "/w2.png",
    link: "//wa.link/a6w9de",
    href: "//wa.link/a6w9de",
    icon: "fa-brands fa-whatsapp",
  },
  {
    id: 3,
    text: "Linkedin",
    avatar: "/w2.png",
    link: "//www.linkedin.com/in/santiago-semino-arquitectos-60406218b/",
    href: "//www.linkedin.com/in/santiago-semino-arquitectos-60406218b/",
    icon: "fa-brands fa-linkedin",
  },
  {
    id: 4,
    text: "Instagram",
    avatar: "/w2.png",
    link: "//www.instagram.com/ssa_estudio/",
    href: "//www.instagram.com/ssa_estudio/",
    icon: "fa-brands fa-instagram",
  },
  {
    id: 5,
    text: "Facebook",
    avatar: "/w2.png",
    link: "//www.facebook.com/ssaestudio?locale=es_LA",
    href: "//www.facebook.com/ssaestudio?locale=es_LA",
    icon: "fa-brands fa-facebook-messenger",
  },
];
//mobile

export const mobile = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "md1",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "md2",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "md",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "Productos",
    name: "md3",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "md4",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "md5",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "md6",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "md7",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "md",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "md",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "md",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "md",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];

//mobiliario

export const mobiliario = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "MOBILIARIO",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "MOBILIARIO",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "productos",
    name: "MOBILIARIO",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "MOBILIARIO",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "MOBILIARIO",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "MOBILIARIO",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "aMOBILIARIOrq5",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "aMOBILIARIOrq4",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "MOBILIARIO",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "MOBILIARIO",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "MOBILIARIO",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];

//modular

export const modular = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "MODULAR",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "MODULAR",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "productos",
    name: "MODULAR",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "MODULAR",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "MODULAR",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "MODULAR",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "MODULAR",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "MODULAR",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "MODULAR",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "MODULAR",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "MODULAR",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];
// MODULOS
export const modulos = [
  {
    id: 1,
    proyect: "Exibicion de arte",
    name: "Recyclable1",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    ubi: "galeria de arte sidney",
    img: "/e1.png",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Exibicion",
  },
  {
    id: 2,
    proyect: "Moda",
    name: "Recyclable1",
    ubi: "galeria de arte auckland",
    img: "/e2.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Moda",
  },
  {
    id: 3,
    proyect: "Productos",
    name: "Recyclable1",
    ubi: "galeria de arte dobrazil",
    img: "/e3.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 1999,
    link: "/Productos",
  },
  {
    id: 4,
    proyect: "Edificios",
    name: "Recyclable1",
    ubi: "galeria de arte otawa",
    img: "/e4.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Edificios",
  },
  {
    id: 5,
    proyect: "Muebles",
    name: "MR & Recyclable1",
    ubi: "galeria de arte japon",
    img: "/e5.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Muebles",
  },
  {
    id: 6,
    proyect: "Interiores",
    name: "Recyclable1",
    ubi: "galeria de arte rusia",
    img: "/e6.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2023,
    link: "/Interiores",
  },
  {
    id: 7,
    proyect: "Interiores",
    name: "Recyclable1",
    ubi: "galeria de arte crespo",
    img: "/e7.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2021,
    link: "/Interiores",
  },
  {
    id: 8,
    proyect: "Interiores",
    name: "Recyclable1",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 9,
    proyect: "Interiores",
    name: "Recyclable1",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 10,
    proyect: "Interiores",
    name: "Recyclable1",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
  {
    id: 11,
    proyect: "Interiores",
    name: "Recyclable1",
    img: "/e8.png",
    descripcion:"  ¿Dónde fue creada la arquitectura Arquitectura: todo lo que debes saber de esta disciplina ... El concepto arquitectura proviene del latín architectura que, a su vez, tiene origen en el griego, y puede definirse como el arte y la técnica de proyectar y construir edificios para satisfacer lasnecesidades del ser humano, a través de la forma, la funcionalidad y los preceptos estéticos.Cuándo fue creada la arquitecturaPrincipios de la arquitecturaunque ya en el año 7.000 A.C ya surgieron los primeros monumentos, la arquitectura, como tal, no se empieza a considerar hasta la edad griega. Desde entonces, se puede percibir una evolución totalmente visible, gracias a que aún siguen vigentes los estilos arquitectónicos más antiguos",
    photo1:"/photo1.jpg",
    photo2:"/photo2.jpg",
    photo3:"/photo3.jpg",
    photo4:"/photo4.jpg",
    activites: 10,
    places: 12,
    days: "1week",
    year: 2022,
    link: "/Interiores",
  },
];
//galery
export const galery = [
  {
    id: 1,
    proyect: "Arquitectura",
    name: "Arquitectura",
    img: "/g5.jpg",
    activites: 10,
   /*  places: 32, */
    days: "1week",
    price: 1.2,
    link: "/Arquitectura",
  },
  {
    id: 2,
    proyect: "CONCURSOS",
    name: "Concursos",

    img: "/g6.jpg",
    activites: 1450,
    /* places: 132, */
    days: "1week",
    price: 1.2,
    link: "/Concursos",
  },
  {
    id: 3,
    proyect: "DISEÑO MOBILIARIO",
    name: "Mobiliario",
    img: "/g1.jpg",
    activites: 23,
   /*  places: 54, */
    days: "1week",
    price: 1.2,
    link: "/Mobiliario",
  },
  {
    id: 4,
    proyect: "ARQUITECTURA MODULAR",
    name: "Modulos",
    img: "/g7.jpg",
    activites: 10,
    /* places: 200, */
    days: "1week",
    price: 1.2,
    link: "/Modulos",
  },
  {
    proyect: "MOBILE",
    name: "Mobile ",
    
    img: "/g2.jpg",
    id: 5,
    activites: 45,
    /* places: 46, */
    days: "1week",
    price: 1.2,
    link: "/MobileDesigne",
  },
 
];
//servicios

export const servicios = [
  {
    id: 1,
    name: "PROYECTOS DE ARQUITECTURA",
    links: [
      { name: "Hotel Nhow Berlín", link: "/ASD4" },
      { name: "Fun Factory Múnich", link: "/ASD5" },
      { name: "kado", link: "/ASD6" },
    ],
    descripcion: `Diseñamos proyectos de arquitectura a medida, como viviendas, edificios en altura, edificios comerciales,
    edificios de usos múltiples, proyectos de urbanismo y paisajismo. La sustentabilidad y el diseño eficiente
    aparecen en nuestros primeros bocetos, como parte conjunta de nuestro proceso.Los proyectos están divididos en 4 diferentes etapas:`,
    descripcion1: `1. ESTUDIO PRELIMINAR
    Es el estudio inicial del proyecto, donde analizamos el pedido del cliente, y empezamos a diseñarlo.
    De estos primeros bocetos podemos empezar a estimar que sistema constructivo es más eficiente
    según el pedido del cliente, cantidad de metros cubiertos, etc.
    con estos primeros datos podemos hacer un costo estimado de obra, y empezar a definir el
    programa de necesidades junto con el cliente.`,
    descripcion2: `2. ANTEPROYECTO
    Una vez definida la primera etapa, pasamos al anteproyecto, donde empezaremos a diseñar el
    proyecto requerido. En esta etapa entra la parte sustentable, y empieza a mezclarse con el diseño
    del proyecto. En esta etapa se le empieza a mostrar al cliente, cierta planimetría y una maqueta
    digital, donde se podrá ver la volumetría propuesta, junto con la estructura, y algunos espacios
    exteriores e interiores. En esta etapa ajustamos el presupuesto de obra estimativo, para que el
    cliente vaya tomando dimensión del mismo. El Anteproyecto debe cumplir con las disposiciones del
    Reglamento de Edificación vigente de la ciudad donde se va a implantar el proyecto.`,
    descripcion3: `3. LEGAJO EJECUTIVO
    En esta etapa vamos a poder definir, instalaciones generales, terminaciones finales, la materialidad y
    las terminaciones interiores, y es cuando empezamos a diseñar el mobiliario. Una vez terminada esta
    etapa, se le entrega al cliente una carpeta con toda la planimetría, junto con un cómputo metrico y
    un presupuesto ajustado al cómputo correspondiente. Esta carpeta cumplirá con las disposiciones
    del Reglamento de Edificación e incluirá toda la información necesaria para que el constructor
    confeccione los planos de ejecución correspondientes a la ingeniería de detalle.`,
    descripcion4: `4. GESTIÓN MUNICIPAL
    Permiso de Edificación:
    Para la habilitación y/o permiso de edificación el arquitecto a cargo deberá presentar el
    legajo correspondiente en el colegio de arquitectos y pagar sus respectivos aportes, una vez
    hecho este trámite, deberá presentar el legajo municipal, el cual deberá incluir toda la
    información requerida por el municipio correspondiente.
    Final de Obra
    Este trámite se gestionará y presentará una vez finalizada la obra, presentando las
    correcciones o planos adicionales correspondientes según la reglamentación de cada
    municipio.`,
  },
  {
    id: 2,
    name: "GESTIÓN, PLANIFICACIÓN Y DIRECCIÓN DE OBRAS",
    links: [
      { name: "Hotel Nhow Berlín", link: "/ASD4" },
      { name: "Fun Factory Múnich", link: "/ASD5" },
      { name: "kado", link: "/ASD6" },
    ],
    descripcion: `Nos encargamos del servicio Gestión, Planificación y Dirección de Obras de todo tipo de
    escala y complejidad, coordinando y haciendo el control de calidad de las tareas de los
    diferentes contratistas, semanalmente presentamos un informe con la certificacion semanal
    de la obra.
    `,
    descripcion1: `(PRUEBA) semanalmente presentamos un informe con la certificacion semanal
    de la obra.`,
    /* descripcion2: `Todos los presupuestos aprobados de la obra se deberán entregar al Director de Obra, quien
    actualiza la planilla de Cómputo y Presupuesto y deberá presentar la certificación semanal de la
    obra.
    `,
    descripcion3: `LA TAREA DEL DIRECTOR DE OBRA ES EL CONTROL Y LA COORDINACIÓN DE LAS TAREAS`, */
  },
  {
    id: 3,
    name: "DISEÑO DE MOBILIARIO",
    links: [
      { name: "Hotel Nhow Berlín", link: "/ASD4" },
      { name: "Fun Factory Múnich", link: "/ASD5" },
      { name: "kado", link: "/ASD6" },
    ],
    descripcion:
    `Diseñamos el mobiliario de cocina con los sistemas de apertura de vanguardia, los muebles
    para baños, y los muebles a medida que el proyecto requiera. Estamos desarrollando una marca de mobiliario y objetos, diseñados y fabricados con el
    concepto del diseño sustentable, estos muebles estan fabricados con materiales que
    provienen del proceso del reciclado.`,
    descripcion1:
    `ES POR ESO QUE BUSCAMOS LA OPTIMIZACIÓN DEL PROCESO, EXPLORANDO NUEVOS
    MATERIALES QUE PROVIENEN DEL PROCESO DEL RECICLADO, CON UNA GRAN
    VERSATILIDAD EN SUS COLORES Y TEXTURAS.
    NUESTRA MISIÓN ES PODER CONCIENTIZAR DESDE EL DISEÑO Y EL PROCESO DEL
    RECICLADO A COLABORAR CON EL CUIDADO DEL MEDIO AMBIENTE.
    `,
  },
  {
    id: 4,
    name: "DISEÑO DE ESTRUCTURAS MODULARES",
    links: [
      { name: "Hotel Nhow Berlín", link: "/ASD4" },
      { name: "Fun Factory Múnich", link: "/ASD5" },
      { name: "kado", link: "/ASD6" },
    ],
    descripcion:
    `Diseñamos y fabricamos estructuras modulare, estas estructuras se prearman en una fabrica
    y van directamente armadas al terreno, donde deberan estar las instalaciones previas y los
    apoyos para recibir el modulo.
   `,
    descripcion1:
    `
    Estos sistemas modulares, tienen muy buena eficiencia acústica y térmica interior, este
    sistema constructivo logra generar un menor impacto ambiental que el que genera una
    construcción tradicional, ya que se generan menos residuos, menos ruido en el terreno, y
    menor consumo de recursos naturales. Estos sistemas pueden instalarse sobre cualquier
    terreno, son flexibles, de bajo mantenimiento, y reemplazan los sistemas constructivos
    tradicionales, por obras más limpias, más rápidas, eficaces y sustentables, con sistemas de
    instalaciones de servicios de vanguardia, estos módulos pueden generar su propia energía y
    reutilizar el agua de lluvia.`,
    descripcion2:
    `
    
    La prefabricación de estos módulos logra optimizar los recursos durante la fase de
    construcción, y así reducir los costos al mínimo, sin la posibilidad de que haya sobreprecios.
    `,
    descripcion3:`
    1. VELOCIDAD CONSTRUCTIVA
    La construcción modular logra optimizar los tiempos de ejecución de la obra y los plazos de
    entrega gracias al proceso de fabricación o pre armado en taller o in situ.
    2. FLEXIBILIDAD
    Una de las alternativas de este sistema es la versatilidad que ofrece, ya que permite su
    instalación en cualquier entorno y condición climática. Este sistemas tienen la virtud de
    poder ir creciendo libremente dependiendo de cada necesidad. Se pueden ir agregando
    módulos en el tiempo a medida que se requiera para ampliar o modificar lo existente en
    busca de nuevos espacios.
    3. COSTOS
    Por su grado de automatización alcanzar un costo exacto del precio final del producto, sin
    riesgos de sobreprecios.
    4. RESISTENCIA
    Estos módulos resisten en perfectas condiciones los movimientos de grúas, tano como izados,
    traslados y descarga hasta su lugar de ensamblaje.
    5. SUSTENTABILIDAD
    La construcción modular permite una disminución del impacto ambiental en el terreno,
    debido a que se produce una menor cantidad de desperdicios, también produce menos
    ruidos. La construcción modular es también reciclable, ya que se puede trasladar y reubicar
    en otro terreno.
   
    `,
  },
  
];

